"""x

Revision ID: 4fd8f52c077f
Revises: aebb6d3a6722
Create Date: 2025-07-03 14:47:05.598160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd8f52c077f'
down_revision: Union[str, None] = 'aebb6d3a6722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_versions', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violation_versions', 'status')
    # ### end Alembic commands ###
