"""xxx

Revision ID: 53038803caaa
Revises: ba9047188456
Create Date: 2025-06-30 19:23:48.929899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53038803caaa'
down_revision: Union[str, None] = 'ba9047188456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_versions', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('violation_versions', sa.Column('update_from_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'violation_versions', 'violation_versions', ['update_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violation_versions', type_='foreignkey')
    op.drop_column('violation_versions', 'update_from_id')
    op.drop_column('violation_versions', 'notes')
    # ### end Alembic commands ###
