"""sss

Revision ID: 6bd923fd80ab
Revises: 07abb165dabd
Create Date: 2025-06-10 18:13:26.835052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd923fd80ab'
down_revision: Union[str, None] = '07abb165dabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'email')
    op.drop_column('tickets', 'name')
    # ### end Alembic commands ###
