"""x

Revision ID: 76f3542aaafb
Revises: f580ed7d085f
Create Date: 2025-06-09 10:01:16.295274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f3542aaafb'
down_revision: Union[str, None] = 'f580ed7d085f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'violations', 'violation_versions', ['version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_column('violations', 'version_id')
    # ### end Alembic commands ###
