"""x

Revision ID: 8cb066f5f50f
Revises: 4fd8f52c077f
Create Date: 2025-07-04 10:07:23.349424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb066f5f50f'
down_revision: Union[str, None] = '4fd8f52c077f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_versions', sa.Column('source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ticket_versions', 'ticket_versions', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_versions', type_='foreignkey')
    op.drop_column('ticket_versions', 'source_id')
    # ### end Alembic commands ###
