"""xxx

Revision ID: aebb6d3a6722
Revises: 53038803caaa
Create Date: 2025-06-30 19:41:05.703827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebb6d3a6722'
down_revision: Union[str, None] = '53038803caaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_versions', sa.Column('source_id', sa.UUID(), nullable=True))
    op.drop_constraint('violation_versions_update_from_id_fkey', 'violation_versions', type_='foreignkey')
    op.create_foreign_key(None, 'violation_versions', 'violation_versions', ['source_id'], ['id'])
    op.drop_column('violation_versions', 'update_from_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_versions', sa.Column('update_from_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'violation_versions', type_='foreignkey')
    op.create_foreign_key('violation_versions_update_from_id_fkey', 'violation_versions', 'violation_versions', ['update_from_id'], ['id'])
    op.drop_column('violation_versions', 'source_id')
    # ### end Alembic commands ###
