"""Reschema

Revision ID: b61dd356db33
Revises: 02f39e9fdab6
Create Date: 2025-06-13 05:03:43.975015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61dd356db33'
down_revision: Union[str, None] = '02f39e9fdab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'avatar_path')
    op.drop_constraint('violations_version_id_key', 'violations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('violations_version_id_key', 'violations', ['version_id'])
    op.add_column('officers', sa.Column('avatar_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
