"""xx

Revision ID: ba9047188456
Revises: b30278135453
Create Date: 2025-06-14 11:54:26.582213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9047188456'
down_revision: Union[str, None] = 'b30278135453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_versions', 'file_path')
    op.drop_column('tickets', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ticket_versions', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
