"""Reschema

Revision ID: bf4d60f24715
Revises: b61dd356db33
Create Date: 2025-06-13 05:06:24.725384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4d60f24715'
down_revision: Union[str, None] = 'b61dd356db33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('officers', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('officers', 'hashed_password')
    # ### end Alembic commands ###
