"""x

Revision ID: f2daaaf700f3
Revises: 
Create Date: 2025-05-27 00:16:24.351469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2daaaf700f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('frame_image_path', sa.String(), nullable=False),
    sa.Column('vehicle_image_path', sa.String(), nullable=False),
    sa.Column('lp_image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    # ### end Alembic commands ###
