services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

    volumes:
      - ./public:/app/public
