name: Build & Push Multiple Services

on:
  push:
    branches: [main]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏷️ Set tags
        id: meta
        run: |
          echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "LATEST=latest" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

      - name: 🛠️ Build & Push Backend
        run: |
          docker build -t $USERNAME/violation-backend:$TAG -t $USERNAME/violation-backend:$LATEST ./backend
          docker push $USERNAME/violation-backend:$TAG
          docker push $USERNAME/violation-backend:$LATEST

  build-yolo-consumer:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏷️ Set tags
        id: meta
        run: |
          echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "LATEST=latest" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

      - name: 🛠️ Build & Push Yolo Consumer
        run: |
          docker build \
            -f ./backend/kafka_handlers/docker_yolo_image/Dockerfile \
            -t $USERNAME/violation-yolo-consumer:$TAG \
            -t $USERNAME/violation-yolo-consumer:$LATEST \
            ./backend
          docker push $USERNAME/violation-yolo-consumer:$TAG
          docker push $USERNAME/violation-yolo-consumer:$LATEST
